### ISSUE TITLE
collectstatic is failing because collect8.svg is missing

### ISSUE THREAD

**Issue by jseppi** [18F/calc#772]
```sh
whitenoise.storage.MissingFileError: The file 'frontend/built/img/correct8.svg' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7fed6952e9b0>.
The CSS file 'frontend/built/style/main.min.css' references a file which could not be found: frontend/built/img/correct8.svg
```

Looks like the missing svg is referenced in `uswds/_inputs.scss`:

```scss
input[type="checkbox"]:checked + label::before {
  background-image: url('../img/correct8.png');
  background-image: url('../img/correct8.svg');
  background-position: 50%;
  background-repeat: no-repeat;
}
```
